Repository vmware/vrealize-orchestrator-plugin-for-alb, pull requests merged in 2023-10, with the labels that each got.

#193 Auto updated assets for vro 22.1.5
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/ControllerProperties.java
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/DnsServiceApplicationProfile.java
Labels: AUTO PR

#195 Auto updated assets for vro eng
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/Constants.java
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/AlertSyslogConfig.java
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/EventDetails.java
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/RoutingService.java
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/ServiceEngineGroup.java
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/StreamingSyslogConfig.java
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/VcenterCloudDeleteDetails.java
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/WafCRS.java
Labels: AUTO PR

#197 Auto updated assets for vro eng
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/Constants.java
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/ALBServicesConfig.java
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/DnsServiceApplicationProfile.java
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/PulseServicesSessionConfig.java
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/PulseServicesTenantConfig.java
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/SessionHeaders.java
Labels: AUTO PR

#196 Cherry-pick all vRO plugin changes and fixes to 22.1.5 branch.
  o11nplugin-vro-core/pom.xml
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/AviVroClient.java
  o11nplugin-vro-package/pom.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/CreateSegmentPool.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/deleteObject.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/fetchNetworkSubnet.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/fetchObjectLists.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/fetchObjectsNames.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/getDNSProvider.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/getExistingObjectsWithController.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/remoteAuthenticationConfiguration.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/updatePool.xml
  o11nplugin-vro/pom.xml
  pom.xml
  version.txt
Labels: Cherry-pick

#198 Cherry-pick all plugin changes and fixes to 30.1.1 branch.
  o11nplugin-vro-core/pom.xml
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/AviVroClient.java
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/CreateSegmentPool.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/createHealthMonitorObj.element_info.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/createHealthMonitorObj.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/deleteObject.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/fetchNetworkSubnet.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/fetchObjectLists.element_info.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/fetchObjectLists.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/fetchObjectsNames.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/getDNSProvider.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/getExistingObjectsWithController.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/remoteAuthenticationConfiguration.xml
  o11nplugin-vro-package/src/main/resources/ScriptModule/com/vmware/actions/updatePool.xml
  o11nplugin-vro-package/src/main/resources/Workflow/Library/vro/Delete Vs with dependent objects using model deprecated.element_info.xml
  o11nplugin-vro-package/src/main/resources/Workflow/Library/vro/Delete Vs with dependent objects using model deprecated.xml
  o11nplugin-vro-package/src/main/resources/Workflow/Library/vro/Reconfigure Virtual service deprecated.element_info.xml
  o11nplugin-vro-package/src/main/resources/Workflow/Library/vro/Reconfigure Virtual service deprecated.xml
  o11nplugin-vro-package/src/main/resources/Workflow/Library/vro/VS creation with public cloud.xml
Labels: Cherry-pick

#200 Auto updated assets for vro 22.1.5
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/StreamingSyslogConfig.java
Labels: AUTO PR

#201 Auto updated assets for vro eng
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/ALBServicesConfig.java
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/ControllerCloudLimits.java
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/NsxtTier1SegmentManualMode.java
Labels: AUTO PR

#202 Bump up the org.json package verison from 20230227 to 20231013.
  o11nplugin-vro-core/pom.xml
Labels: dependencies

#203 Auto updated assets for vro eng
  o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/model/MetricsEventThreshold.java
Labels: AUTO PR
